apiVersion: ctlptl.dev/v1alpha1
kind: Registry
name: ruby-to-s3-registry
port: 5000
---
apiVersion: ctlptl.dev/v1alpha1
kind: Cluster
name: kind-ruby-to-s3-dev
product: kind
registry: ruby-to-s3-registry
kindV1Alpha4Cluster:
  nodes:
    - role: control-plane
  featureGates:
    SidecarContainers: true
