services:
  localstack:
    image: localstack/localstack:3.0.2
    environment:
      - SERVICES=sqs,s3
      - USE_SINGLE_REGION=1
      - AWS_DEFAULT_REGION=ap-northeast-1
      - PERSISTENCE=1
    volumes:
      - ./docker/localstack/init/ready.d:/etc/localstack/init/ready.d
      - localstack-data:/var/lib/localstack:delegated
    ports:
      - 4566:4566
volumes:
  localstack-data:
