apiVersion: batch/v1
kind: Job
metadata:
  name: completed
  labels:
    app: no-sidecar
    app.kubernetes.io/part-of: worker
    mshr.dec/use-sidecar: "true"
    called-previously: self-sidecar
spec:
  template:
    metadata:
      labels:
        app: completed
        app.kubernetes.io/part-of: worker
        mshr.dec/use-sidecar: "true"
    spec:
      # shareProcessNamespace: true
      restartPolicy: Never
      containers:
        - name: ruby
          image: ruby-to-s3:latest
          imagePullPolicy: Never
          args:
            - "logging:sidecar[true]"
          volumeMounts:
            - mountPath: /var/log
              name: log
        - name: vector
          image: "timberio/vector:0.37.0-distroless-libc"
          args:
            - --config-dir
            - /etc/vector/
          env:
            - name: AWS_REGION
              value: us-west-2
            - name: AWS_ACCESS_KEY_ID
              value: minioadmin
            - name: AWS_SECRET_ACCESS_KEY
              value: minioadmin
            - name: VECTOR_LOG
              value: "info"
          volumeMounts:
            - name: data
              mountPath: "/vector-data-dir"
            - name: config
              mountPath: "/etc/vector/"
              readOnly: true
            - name: log
              mountPath: /var/log
      volumes:
        - name: log
          emptyDir: {}
        - name: config
          configMap:
            name: completed
        - name: data
          emptyDir: {}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: completed
data:
  agent.yaml: |
    data_dir: /vector-data-dir
    api:
      enabled: false
      # address: 127.0.0.1:8686
      # playground: false
    sources:
      file:
        type: "file"
        include: [ "/var/log/stdout.log" ]
    sinks:
      s3_archives:
        inputs: ["file"]
        type: "aws_s3"
        region: "us-east-1"
        bucket: "ruby-to-s3"
        endpoint: "http://192.168.0.118:14566"
        batch:
          timeout_secs: 60
        compression: "none"
        key_prefix: "sidecar/12/%F"
        filename_append_uuid: false
        encoding:
          codec: "text"
