apiVersion: v1
kind: ConfigMap
metadata:
  name: vector
data:
  agent.yaml: |
    data_dir: /vector-data-dir
    api:
      enabled: true
      address: 127.0.0.1:8686
      playground: false
    sources:
      file:
        type: "file"
        include: [ "/var/log/stdout.log" ]
    sinks:
      s3_archives:
        inputs: ["file"]
        type: "aws_s3"
        region: "us-east-1"
        bucket: "ruby-to-s3"
        endpoint: "http://10.0.249.213:4566"
        batch:
          timeout_secs: 60
        compression: "none"
        key_prefix: "sidecar/1/%F"
        filename_append_uuid: false
        encoding:
          codec: "text"
