apiVersion: batch/v1
kind: Job
metadata:
  name: self-sidecar
spec:
  template:
    metadata:
      labels:
        app: self-sidecar
    spec:
      restartPolicy: Never
      containers:
        - name: ruby
          image: ruby-to-s3:latest
          imagePullPolicy: Never
          args:
            - "logging:sidecar"
          volumeMounts:
            - mountPath: /var/log
              name: log
        - name: vector
          image: "timberio/vector:0.37.0-distroless-libc"
          args:
            - --config-dir
            - /etc/vector/
          env:
            - name: AWS_REGION
              value: us-west-2
            - name: AWS_ACCESS_KEY_ID
              value: dummy
            - name: AWS_SECRET_ACCESS_KEY
              value: dummy
            - name: VECTOR_LOG
              value: "info"
            - name: VECTOR_SELF_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: VECTOR_SELF_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: VECTOR_SELF_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: PROCFS_ROOT
              value: "/host/proc"
            - name: SYSFS_ROOT
              value: "/host/sys"
          volumeMounts:
            - name: data
              mountPath: "/vector-data-dir"
            - name: config
              mountPath: "/etc/vector/"
              readOnly: true
            - name: log
              mountPath: /var/log
      volumes:
        - name: log
          emptyDir: {}
        - name: config
          configMap:
            name: self-vector
        - name: data
          emptyDir: {}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: self-vector
data:
  agent.yaml: |
    data_dir: /vector-data-dir
    api:
      enabled: false
      # address: 127.0.0.1:8686
      # playground: false
    sources:
      file:
        type: "file"
        include: [ "/var/log/stdout.log" ]
    sinks:
      s3_archives:
        inputs: ["file"]
        type: "aws_s3"
        region: "us-east-1"
        bucket: "ruby-to-s3"
        endpoint: "http://10.0.249.211:4566"
        batch:
          timeout_secs: 15
        compression: "none"
        key_prefix: "sidecar/1/%F"
        filename_append_uuid: false
        encoding:
          codec: "text"
